- inc/crn_decomp.h
In Daemon these were originally done by commit fc5c77c5568bae76e6b421121d0721357ae503f9 "Port crnlib to Mac" by Amanieu. The changes were lost by switching to the Unity fork.
> Re-apply fixes for Mac compilation.

- CMakeLists.txt
build executables in cmake output dir, not in subdirectories
basically builds crunch as `build/crunch` instead of `build/crunch/crunch`
> build executables in cmake output dir, not in subdirectories

- inc/crn_decomp.h
This fix is enough to enable crn decompression in third-party projects
> FreeBSD: fix malloc in crn_decomp single header file

- crnlib/crn_platform.h
- Guard added to GCC definition of CRNLIB_BREAKPOINT. Fixes compilation on ARM platforms
> crn_platform: No inline x86 asm on non-x86

- inc/crn_decomp.h
crn_decomp.h uses uintptr_t but does not #include the file defining it. Seems to compile fine with g++ on a modern machine, but fails on Xonotic's srv03 (Ubuntu LTS).
Change is hopefully safe, assuming all supported platforms actually have stdint.h. If they don't, though, why would they even know uintptr_t?
> crn_decomp: #include <stdint.h> to get uintptr_t.

- crnlib/Makefile
No longer hardcode the compiler to be g++ (g++ on srv03 is too old, but clang++ works).
Also, split up the COMPILE_OPTIONS into separate flags so one can easily remove the -march=core2 flag (by "make COMPILE_CPU_OPTIONS="). Helps with compiling on ARM64 (binary seems to work BTW).
> Makefile fixes to compile on srv03 and my ARM64 laptop

- flake.nix
A nix flake allows building and running the software with the Nix
package manager, used in NixOS or standalone. You can consider as
a package or repo description.
In particular, this is used for the Unvanquished Nightly Server.
> Add nix flake support

- crunch/crunch.cpp
The builtin help said:
> -helperThreads # - Set number of helper threads, 0-16, default=(# of CPU's)-1
But using a number above 15 (like 16) printed:
> Warning: Value 16 for parameter "helperThreads" is out of range, clamping to 15
Since the maximum value is hardcoded as cCRNMaxHelperThreads we may even rely
on that builtin limit to always be correct.
> Fix help about `-helperThreads`, use `cCRNMaxHelperThreads`

- crnlib/crn_mipmapped_texture.cpp
- crnlib/crn_mipmapped_texture.h
- crunch/crunch.cpp
Add `-noNormalDetection` to avoid normal map detection
Crunch has an algorithm to try to detect normal maps, probably to pick higher quality compressors.
It prevents the compressor to wrongly detect a normal map and select formats like `DXT5_AGBR` when `DXT1` is good enough.
It does not only avoid to produce files in less supported swizzled formats, it also allows to pick smaller formats, sometime saving half of the produced file size.
> Add `-noNormalDetection` to avoid normal map detection

- crnlib/crn_command_line_params.cpp
- crunch/crunch.cpp
My routine to get help was:
```
$ crunch -h
Error: Unrecognized command line parameter: "-h"
Exit status: 1
$ crunch --help
Error: Unrecognized command line parameter: "--help"
Exit status: 1
$ crunch
Error: No command line parameters specified!
Command line usage:
[…]
Exit status: 1
```
Now I can do:
```
$ crunch -h
Command line usage:
[…]
Exit status: 0
```
Long options `--help` is also available, and `/?` is available on Windows as well.
> crunch: add -h option to print help

- inc/crnlib.h
According to the Unity forums the Unity game engine now expects m_userdata0 value to be 1 for files produced by this tool with this format to be loaded.
See https://forum.unity.com/threads/crunch-textures.522787/#post-4282222 
This is very likely to recognize files produced by the now-incompatible old crunch tool.
At some point we may print a warning when reading files using the 0 value. This would allow softwares like the Dæmon game engine to inform the user that maybe the file is not compatible because it may have been produced with an incompatible tool.
At some point we may even add an optional mechanism to not load files using the 0 value for software that will never have to read CRN files using new Unity format but with old number m_userdata0 0.
For example, once we would have …
> Bump m_userdata0 to 1 to produce files openable with latest Unity game engine

- crunch/crunch.cpp
This tool being incompatible with the one by Binomial, redirecting people to the email address of Binomial is wrong for everyone.
> crunch: update bug report instructions

- crunch/crunch.cpp
The tool builds and runs on other systems, so reporting x64 on arm64 may be confusing.
The internal wording is kept as is at it is probably not a good idea to gratuitously introduce diff noise with upstream.
> crunch: report 32-bit or 64-bit instead of x86 or x64

- crnlib/crn_jpge.cpp
- crnlib/crn_mem.cpp
- crnlib/crn_threading_pthreads.cpp
- crnlib/crn_timer.cpp
Those commits improves the build of the `crunch` tool on FreeBSD.
Until now, only the `crnlib` was buildable on FreeBSD when integrated in another tool (for example, NetRadiant):
- https://github.com/DaemonEngine/crunch/pull/12
Now the `crunch` command line tool builds as well, if that other MR is merged:
- https://github.com/DaemonEngine/crunch/pull/38
The `crunch` tool will build but will not run properly until aligned allocation is enforced, see:
- https://github.com/DaemonEngine/crunch/pull/36
We need that other patch to avoid getting those errors at run time:
```
crunch/crnlib/crn_mem.cpp(125): Assertion failed: "crnlib_free: bad ptr"
crunch/crnlib/crn_mem.cpp(125): Assertion failed: "crnlib_realloc: bad ptr"
```
---
Original message:
This is a list of commits aiming to fix crunch …
> Improve build on FreeBSD

- crnlib/crn_platform.h
crunch: use `_FILE_OFFSET_BITS 64` with `fopen`/`fseek`/`ftell` outside of Linux.
It seems to work on macOS and FreeBSD without requiring specific `#ifdef` for any them. It also works on Linux but
we may still prefer `*64` variants to avoid ambiguity.
_Note_: If needed, `minizip/ioapi.h` is known to provide more compatibility code for old MSVC too, but what we have looks good enough on that part.
> crunch: use `_FILE_OFFSET_BITS 64` with `fopen`/`fseek`/`ftell` outside of Linux

- crnlib/crn_find_files.cpp
`readdir()` doesn't support file detection on all file systems, so we use `stat()` as a fallback.
This makes the `crunch` tool works with files stored over the network on NFS shares on MacOS.
We also report if the current code fails to detect if a path is a file or a directory, just in case some other corner case surfaces.
It fixes:
- https://github.com/DaemonEngine/crunch/issues/37
> crunch: other way to detect if a path is a file or a directory

- CMakeLists.txt
- inc/crn_decomp.h
- inc/crn_defs.h
The CRC implementation is slow and who cares if 1 pixel is wrong?
> Allow validating the header without CRCing the entire file

- crnlib/crn_vector.cpp
- inc/crn_decomp.h
Remove obsolete `sprintf` calls.
> Remove obsolete sprintf calls

- README.md
Very minor, we don't make use of it ourselves, I just wanted to check if the documentation was still correct.
> readme: fix emcc command

- CMakeLists.txt
Rewrite the options and the flag setting
- Add USE_LTO to enable LTO,
enabled by default.
- Add USE_EXTRA_OPTIMIZATION to also enable -O3 when it is not used by default
enabled by default.
- Add USE_FAST_MATH, to produce reproducible CRN files this should be disabled,
enabled by default.
- Increase warning verbosity level.
- Generate maximum amount of debug information, including macro definitions.
- Always disable strict aliasing, the code requires it to always be disabled.
Fixes #29:
- https://github.com/DaemonEngine/crunch/issues/29
> cmake: rewrite the build options and the flag setting

- cmake/cross-toolchain-mingw32.cmake
- cmake/cross-toolchain-mingw64.cmake
- crnlib/crn_arealist.cpp
- crnlib/crn_dynamic_string.cpp
- crnlib/crn_platform.cpp
- crnlib/crn_platform.h
- crnlib/crn_vector.cpp
- crnlib/lzma_Types.h
- example2/example2.cpp
- example3/example3.cpp
- inc/crn_decomp.h
- Provide ready-to-use cmake toolchain file for MinGW,
- Fix build on 32-bit MinGW,
- Avoid a warning by not redefining Win32 functions on MinGW,
- Use more Win32 code with MinGW.
> Improve MinGW compatibility

- crnlib/crn_threading_pthreads.cpp
On macOS, `sem_unlink` should be used instead of `sem_destroy`, what the current code does is to call `sem_destroy` on every pthread-compatible system and then call `sem_unlink` on macOS.
It is expected the only macOS implementation of it and other functions like `sem_init` is to do nothing but to exist and be marked as deprecated so the compiler can print warnings as the `-Wdeprecated-declarations` flag is enabled by default.
Because `sem_destroy` is expected to be a stub on macOS and we call `sem_unlink anyway`, the current code works but raises a “'sem_destroy' is deprecated” warning at build time for something we don't need and  we already have the right implementation done anyway.
> crnlib: do not call `sem_destroy` on macOS

- crnlib/crn_arealist.cpp
- crnlib/crn_assert.cpp
- crnlib/crn_console.cpp
- crnlib/crn_dynamic_string.cpp
- crnlib/crn_platform.cpp
- crnlib/crn_platform.h
- crnlib/crn_resample_filters.cpp
- crnlib/crn_strutils.cpp
- crnlib/crn_strutils.h
- crnlib/crn_value.h
- crnlib/lzham_timer.h
- crunch/crunch.cpp
- example1/example1.cpp
- example2/example2.cpp
- example3/example3.cpp
- do not reuse Windows name as alias on non-Windows system,
- do not re-implement functions there is a system implementation for,
- deduplicate implementations for things like `stricmp`,
- avoid doing `ifdef` everywhere.
> Factorize the system-specific function shims like snprintf

- crunch/crunch.cpp
- test/test.py
By default crunch prints some information about the software, this is fine for a one-time usage, but a bit noisy when used in bulk calls, like in a test suite.
Also deduplicate option in options list, and bump some date.
> Add `-noTitle` option to avoid printing the title on every run (makes output less noisy)

- .azure-pipelines.yml
- CMakeLists.txt
- example1/example1.cpp
- example2/example2.cpp
- example2/timer.cpp
- example3/example3.cpp
Now the examples build everywhere, not only on Windows.
I introduced some `ifdef` that may later be rewritten with deeper change by calling into some already implemented multiplatform functions from crnlib, or to implement such reusable multiplatform function, or to make them reusable, but I expect to do that in a second step, the same way I factorized the snprintf code after having made sure it was right.
> Make examples multiplatform

- crnlib/crn_find_files.cpp
The alternate code was testing for the file name in the current directory.
Fixes #63:
- https://github.com/DaemonEngine/crunch/issues/63
> crnlib: correct alternate code to test if a path is a directory

- crnlib/crn_assert.h
- crnlib/crn_command_line_params.cpp
- crnlib/crn_comp.cpp
- crnlib/crn_data_stream_serializer.h
- crnlib/crn_dxt_endpoint_refiner.cpp
- crnlib/crn_dxt_fast.cpp
- crnlib/crn_etc.cpp
- crnlib/crn_file_utils.cpp
- crnlib/crn_helpers.h
- crnlib/crn_image_utils.h
- crnlib/crn_jpgd.cpp
- crnlib/crn_miniz.cpp
- crnlib/crn_mipmapped_texture.cpp
- crnlib/crn_qdxt1.cpp
- crnlib/crn_qdxt5.cpp
- crnlib/crn_resample_filters.cpp
- crnlib/crn_texture_comp.cpp
- crnlib/crn_threading_pthreads.cpp
- crnlib/crn_value.h
- crnlib/lzma_LzmaEnc.cpp
- crnlib/lzma_LzmaLib.cpp
- crunch/corpus_test.cpp
- crunch/crunch.cpp
Fix a bunch of warnings, also delete an unused macro.
> Fix a bunch of warnings

- crnlib/lzma_LzmaEnc.cpp
Fixes #70:
- https://github.com/DaemonEngine/crunch/issues/70
I commented it out instead of deleting it, so if one day we want to update lzma the diff will be more meaningful.
> lzma: do not build an unused function with a dangling pointer warning

- .azure-pipelines.yml
- crnlib/crn_strutils.cpp
- crnlib/crn_strutils.h
- example1/example1.cpp
- example2/example2.cpp
- example3/example3.cpp
- test/test.py
Fixes some bugs in examples and factorize some code.
The examples are now tested in CI.
> Fixes some bugs in examples and factorize some code, test them in CI

- crnlib/crn_lzma_codec.cpp
- crnlib/crn_threading_pthreads.cpp
- g_number_of_processors is defined on every platform
- no need to set default g_number_of_processors to default
> crnlib: g_number_of_processors is defined on every platform

- crnlib/crn_find_files.cpp
Don't stop listing files if there is an unknown file type in a directory, skip it.
> crnlib: don't stop listing files if there is an unknown file type in a directory, skip it

- CMakeLists.txt
Disable fast math by default.
Fast math was initially enabled by default in upstream repository so we inherited that. I noticed that it made the produced images less reproducible, and I added an option to disable fast math, while keeping it enabled by default. I see no performance boost when using fast math so we better favor reproduciblity by default.
Our latest releases were already generated with a crunch built with disabled fast math.
Here are the times when reconverting all images from our `tex-*` packages (`1361` crn files being generated):
build|time
-|-
`-ffast-math -fno-math-errno -ffp-contract=fast`|7m33,276s
`-ffp-contract=off`|7m32,301s
`-ffp-contract=fast`|7m32,208s
I see no reason to sacrifice reproducibility for no other gain in exchange.
I only tested it on Linux with GCC …
> cmake: disable fast math by default

- inc/crn_decomp.h
Fix a warning I get when compiling `q3map2`:
```
[ 42%] Building CXX object libs/crnrgba/CMakeFiles/crnrgba.dir/crn_rgba.cpp.o
[ 42%] Linking C static library libpicomodel.a
In file included from netradiant/libs/crnrgba/crn_rgba.cpp:31:
netradiant/libs/crnrgba/../crunch/inc/crn_decomp.h:1459:12: warning: first argument in call to 'memcpy'
is a pointer to non-trivially copyable type 'crnd::prefix_coding::decoder_tables' [-Wnontrivial-memcall]
1459 |     memcpy(this, &other, sizeof(*this));
|            ^
netradiant/libs/crnrgba/../crunch/inc/crn_decomp.h:1459:12: note: explicitly cast the pointer to silence
this warning
1459 |     memcpy(this, &other, sizeof(*this));
|            ^
|            (void*)
```
> crn_decomp: fix: warning: first argument in call to ‘memcpy’ is a pointer to non-trivially copyable type ‘crnd::prefix_coding::decoder_tables’

- .azure-pipelines.yml
Bump the Linux image versions:
* replace `ubuntu-20.04` that was removed with `ubuntu-22.04`,
* use `ubuntu-24.04` when it's better.
> CI/Azure: bump the Linux image versions
